<template>
  <transition name="modal-fade">
    <div class="modal-backdrop bg-mask upcoming_modal_position" v-on:click.self="userProfileBackdrop">
      <div class="event_invite_modal"
        role="dialog"
        aria-labelledby="modalTitle"
        aria-describedby="modalDescription"
      >
        <header
          class="event_invite_body"
          id="modalTitle"
        >
          <span class="gs_more_span" @click="closeModal">Done</span>
          <div class="gs_more_p">
              
              <p>Regular GS is assigned one public chain, and then you may refer many other GS marketers onto your public chain, this way your commissions and benefits will continue to multiply. Businesses aggregate the transaction income on this public chain, and the percentage of profit from transaction conversion generated by all nodes on this public chain is a benefit of the Regular GS.</p>
              <p>
              Applying for Gold GS will give you the path of the highest return for the transactions generated by all nodes on your public chain, because Gold GS can get the transaction revenue on the two public chains (one Business chain plus GS marketer’s chain), except for the revenue commission associated with the GS public chain, this is a sliding scale, which increases as your revenues increase (refer to the Commissions Chart)   
              </p>
            
          </div>
        </header>
      </div>
    </div>
  </transition>
</template>

<script>

  export default {
    name: 'GS_more',
    components: {
      
    },
    data () {
      return {
        toggle: false,
      }
    },
    methods: {
      close() {
        this.$emit('close');
      },
      closeModal() {
        this.$emit('close');
      },
      userProfileBackdrop(evt) {
        if(evt.target.classList.length > 0 && "bg-mask"){
          this.$emit('user-backdrop');
        }
      },
      handleOpen() {
        this.$emit('handleOpen');
      },
    },
  };
</script>
<style>
  .gs_more_p  {
    margin: 40px 30px;
    font-size: 14px;
    position: relative;
  }
  .gs_more_p p {
    margin: 10px auto;
  }
  .gs_more_span{
    font-size: 16px;
    color: #13C8FF;
    position: absolute;
    top: 10px;
    right: 20px;
  }
</style>
