<template>
  <div>
    <div class="container">
        <div class="phone header_phone">
          <div class="header_modal">
            <router-link to="/socialmedia/bs_center/socialmedia_bs_user_center" class="header_arrow"><img src="img/header_arrow.png"></router-link>
            <a>UPGRADE BUSINESS ACCOUNT</a>
          </div>
          <div class="content left-content header_top">
            <p class="secure_checkout_title">Business Guidelines</p>
            <p class="medium_title">BUSINESS MEMBERSHIP</p>
            <p class="medium_1_title">Regular Business</p>
            <p class="medium_2_title"><b>Option 1</b></p>
            <ul>
              <li>$500 minimum deposit, used for: G-Coins Rewards, CPC G-Coins benefits, conversion sales commissions, sending G-coins to speakers and participants.</li>
              <li>Offer set-up: No fee</li>
              <li> Reload deposits as needed</li>
              <li>No monthly fees.</li>
              <li>Set up and upload ad promotion links and campaign offers at any time.</li>
              <li>Customize traffic promotion plans and pay for all marketing expenses incurred</li>
            </ul>
            <p class="medium_2_title"><b>Option 2</b></p>
            <ul>
              <li>$200 - $499 Deposit required</li>
              <li>$10 set up fee for each promotion link</li>
              <li>Reload deposits as needed</li>
              <li>No monthly fees</li>
              <li>Set up and upload ad promotion links and campaign offers at any time</li>
            </ul>

            <p class="medium_1_title">Business Gold</p>
            <ul>
              <li>Once per year deposit of $3,000, used for G-Coins Rewards, CPC G-Coins benefits, conversion sales commissions, sending G-coins to speakers and audience.</li>
              <li>One free landing page design</li>
              <li>Profile bundle for events (act in both capacities - Business and GS)</li>
              <li>Admin rights for your events.</li>
              <li>Community Admin rights.</li>
              <li>Creation of a direct pay to your events.</li>
              <li>Unlimited number of community event creations.</li>
              <li>Review user removal details.</li>
            </ul>
            <p class="upgrade_gs_para"><b>For Businesses Membership</b><br>
              The difference between Regular and Gold Business members on our platform is, the Regular members assigned only Gold5g store node; while Gold Business members can choose multi-node, such as: Gold5g e-commerce site, business’ own official website and may also choose the designated online e-commerce platforms of other merchants as well.   Important Note: e-commerce platforms must provide back-end tracking code open support, if not, then we can only benefit from CPC paid clicks, not conversion tracking results
            </p>
            <p class="upgrade_gs_para"><b>Gold Platform Node Definition</b><br>
              A node refers to a marketing site designated by a business’s products or service.<br>This site is composed of more than 3 aspects of digital data:<br>1. The product or service data that the business provides<br>2. Sharing link data<br>3. Tracking code data, and<br>4. Marketing Conversion data (including CPC click-through rate, conversion rate data) is generated by the GS Marketer after the information is posted to the public.  The purchase transaction on each node determines the sales benefit for the business on the node.
            </p>
            <p class="medium_title">How it Works For Our Business Partners:</p>
            <ul>
              <li>In GOLD, create and complete your profile.  Setup and post your marketing ad  by entering your offer details with Links, Banners, Video and Content</li>
              <li>Offer Type:</li>
                <ul>
                  <li>Commission rate,</li>
                  <li>CPC G-coin rate,</li>
                  <li>G-Coins rewards,</li>
                </ul>
              <li>Advertising Type</li>
            </ul>
            <div class="CP_images">
              <img src="CPC_sky.png" class="CP_img">
              <img src="CPS_orange.png" class="CP_img">
              <img src="CPA_green.png" class="CP_img">
              <img src="CPL_blue.png" class="CP_img">
              <img src="CPI_purple.png" class="CP_img">
            </div>
            
            <ul>
              <li><b>Branding</b></li>
              <p class="upgrade_buc_desc">Create Events or Communities for your brand or service. Grow your Fan base and build your Brand Matrix, use Events for communicating,  promoting, and sending G-Coins.</p>
              <li><b>Build your incentive program based upon your budget constraints.</b></li>
              <p class="upgrade_buc_desc">Reward your partners including but not limited to G-Coin rewards, CPC G-Coin, as well as conversion commissions.</p>
              <li><b>Business Gold member fee applies to traffic costs. Post your campaign offer details in your account on GOLD.</b></li>
              <p class="upgrade_buc_desc">Tap and go, the campaign will be active.  Invite friends, partners, employees, influencers, marketers, and promote your offers.  The GOLD tracking system will automatically track your campaign conversions.</p>
            </ul>

            <p class="gs_account_link"><router-link class="gs_account_check_link" to="/businessusercenter/business_agreement"><b>Check Business Agreement >></b></router-link></p>

            <p class="medium_title">UPGRADE YOUR ACCOUNT</p>
            <img src="img/logo.svg" class="buc_account_logo">
            <p class="medium_title">Business Gold Membership</p>
            <label class="label_select">
              <input type="radio" checked="checked" name="radio">
              <span class="checkmark"></span>
              <span class="upgrade_account_select">$1000 deposit<br>Choose 1 of the options below.</span>
            </label>
            <label class="label_select">
              <input type="radio" name="radio">
              <span class="checkmark"></span>
              <span class="upgrade_account_select">$2000 deposit<br>Choose 2 of the options below.</span>
            </label>
            <label class="label_select">
              <input type="radio" name="radio">
              <span class="checkmark"></span>
              <span class="upgrade_account_select">$3000 deposit<br>Get all 3 options below.</span>
            </label>
            <p class="business_fee_title">Gold Business Membership fee selection:</p>
            <div class="gs_account_stage_year">
            <select class="form-control gs_account_stage_select">
              <option>1 Year</option>
              <option>2 Year</option>
              <option>3 Year</option>
              <option>4 Year</option>
              <option>5 Year</option>
            </select>
            <p class="stage_orange_price">$1000</p>
            </div>
            <p class="gs_account_stage_date">Renews July 2022 for $3000</p>
            <p class="business_fee_title"><b>Business Gold Membership comes with FREE Features. Select any of the below features that best fits to your business goals.</b></p>
            <form>
              <div>
                <div class="checkbox_check">
                  <input type="checkbox" id="vehicle1" name="vehicle1" value="Bike">
                  <label for="vehicle1"></label>
                  <p>Traffic direct  to Gold5g store, or your own official website, or any other e-commerce platform that you choose (in order to work correctly you must include the GOLD provided tracking pixel).</p>
                </div>
                <div class="checkbox_check">
                  <input type="checkbox" id="vehicle2" name="vehicle2" value="Car">
                  <label for="vehicle2"></label>
                  <p>One landing page design for free; One set of advertising banners (one of each size).</p>
                </div>
                <div class="checkbox_check">
                  <input type="checkbox" id="vehicle3" name="vehicle3" value="Car">
                  <label for="vehicle3"></label>
                  <p>3. Free single payment for 4 Admin items.</p>
                </div>
              </div>
            </form>
            <p class="stage_total">Total Amount<span class="stage_right"><b>$1000</b></span></p>
            <button class="stage_paypal_btn"><img src="img/paypal.png" class="paypal_btn_img">alicedu@goldenlinkplus.com</button>
            <p class="upgrade_gs_para"><b>Note:</b> The deposit is non-refundable<br>This deposit will be used for your various campaign expenses such as GS Coins Rewards Credit, CPC G-Coins benefits, Conversion sales commissions, sending G-coins to event speakers and audience</p>
            <router-link to="/businessusercenter/business_secure_checkout">
              <button class="gs_account_stage_checkout_btn">Checkout
                <img src="reg_next.png" class="glplogo_reg_btn_img">
              </button>
            </router-link>
            <form>
              <div>
                <div class="checkbox_check">
                  <input type="checkbox" id="vehicle1" name="vehicle1" value="Bike">
                  <label for="vehicle1"></label>
                  <p>By conmpleting the sign-up process, I agree to be bound by the <b>Terms & Conditions</b> and <b>Privacy Policy</b> for this website.</p>
                </div>
                <p></p>
                <div class="checkbox_check">
                  <input type="checkbox" id="vehicle2" name="vehicle2" value="Car">
                  <label for="vehicle2"></label>
                  <p>By clicking below I hereby affirm that I am at least 18 years of age and agree to the <b>Terms & Conditions</b></p>
                </div>
              </div>
            </form>
            
          </div>
        </div>
    </div>
  </div>
</template>
<script>

export default {
  name: "Upgrade_Business_Account",
  components: {
    
  },
  data () {
    return {
      
    }
  }
  
}
</script>
<style>
  .header_phone {
    position: relative;
  }
  .medium_2_title {
    margin: 0 20px;
    font-weight: 500;
  }
  .gs_account_check_link {
    color: #13C8FF;
    font-size: 16px;
  }
  .gs_account_link {
    margin: 10px 20px;
  }
  
  .buc_account_logo {
    margin: 0 20px;
  }

  .gs_account_stage_select {
    width: 50% !important;
    background-color: #F4F9FE !important;
    border-color: white !important;
    color: #495057;
    margin: 0 20px;
  }
  .gs_account_stage_year {
    display: flex;
    text-align: right;
  }
  .gs_account_stage_year p {
    margin: 0 0 0 70px ;
    font-size: 14px;
  }
  .gs_account_stage_date {
    text-align: right;
    margin:20px;
  }
  .stage_right {
    float: right;
  }
  .stage_total {
    margin: 20px;
  }
  .stage_paypal_btn {
    border: 1px solid #E8F1FA;
    text-align: center;
    margin: 0 20px 20px 20px;
    width: calc(100% - 40px);
    padding: 5px;
  }
  .paypal_btn_img {
    width: 50px;
    margin-right: 20px;
  }
  input[type=checkbox] {
    display:none;
  }

  input[type=checkbox] + label {
      display:inline-block;
      padding: 0 0 0 0px;
      height: 39px;
      width: 39px;
      background-size: 100%;
      background: url('../../../public/Checkbox_non.png') no-repeat;
      margin: 0;
  }

  input[type=checkbox]:checked + label {
      background: url('../../../public/Checkbox.png') no-repeat;
      width: 39px;
      height: 39px;
      background-size: 100%;
      display:inline-block;
      margin: 0;
  }
  .CP_img {
    margin: auto;
  }
  .CP_images {
    margin: 20px;
    text-align: center;
    display: flex;
  }
  .upgrade_buc_desc {
    margin: 0;
    font-size: 13px;
  }
  .business-diamond_check {
    width: 70%;
  }
  .diamond_logo {
    display: table;
    text-align: left;
    margin: 10px 20px;
  }
  .diamond_logo .check_logo {
    display: table-cell;
    vertical-align: unset;
  }
  .diamond_logo_p {
    font-size: 14px;
    margin-bottom: 0;
  }
  .stage_orange_price {
    margin: 7px 0 0 70px !important;
    font-size: 16px !important;
    color: #F4992D;
  }


  /* The container */
  .label_select {
    display: flex;
    position: relative;
    margin: 10px auto 10px 20px;
    cursor: pointer;
    font-size: 22px;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
  }

  /* Hide the browser's default radio button */
  .label_select input {
    position: absolute;
    opacity: 0;
    cursor: pointer;
  }

  /* Create a custom radio button */
  .checkmark {
    position: absolute;
    top: 2px;
    left: 0;
    height: 39px;
    width: 39px;
    background: url('../../../public/Checkbox_non.png') no-repeat;
    border-radius: 50%;
  }

  /* On mouse-over, add a grey background color */
  /* When the radio button is checked, add a blue background */
  .label_select input:checked ~ .checkmark {
    background: url('../../../public/Checkbox.png') no-repeat;
  }

  /* Create the indicator (the dot/circle - hidden when not checked) */
  .checkmark:after {
    content: "";
    position: absolute;
    display: none;
  }

  /* Show the indicator (dot/circle) when checked */
  .label_select input:checked ~ .checkmark:after {
    display: block;
  }

  .upgrade_account_select {
    font-size: 15px;
    margin: auto auto auto 50px;
  }
  .business_fee_title {
    margin: auto 20px 20px;
    font-size: 14px;
  }
</style>
